Cache arbitrary labels in the SQL database
rancher/lasso pull request #110
Opened 2024-09-24 00:30 UTC by ericpromislow

WIP - no unit tests in yet

2024-09-24 20:44 UTC, ericpromislow commented on pkg/cache/sharedinformerfactory.go
> +}
I first read it expecting it to be used as a closure, and it isn't. But sure, I'll restore it.

2024-09-24 20:46 UTC, ericpromislow commented on pkg/cache/sql/store/store.go
> +	}
I was too, but treat this as a first pass at the problem. I'll look into tracking the labels as a set on each GVK and then don't have to make the sql queries.

2024-09-24 20:47 UTC, ericpromislow commented on pkg/cache/sql/informer/indexer.go
> +		err = i.Store.AddLabels(tx, keys)
Ah, true.  So I need to modify it in the upsert itself...?

2024-09-27 13:02 UTC, moio requested changes
Thanks for your contribution @ericpromislow.

I left an inline comment about the general idea behind the implementation of this feature, as I am a bit unsure if this is the best path. Hopefully that conveys the main idea decently, I am happy to discuss it anytime.

2024-10-10 20:33 UTC, ericpromislow commented
I finally can get back to this. @moio I agree with you that a separate `node_labels` table sounds better than adding columns to each table, and I have no problem with `join`s.

2024-11-06 00:20 UTC, ericpromislow commented
This approach is just wrong. I'm going to create a new PR with a completely different implementation, as suggested here, and will leave this PR as a contrast for reference in the new PR.

2024-11-06 00:20 UTC, closed without merging