Wrap the main and count queries in ListByOptions with a transaction
rancher/lasso pull request #112
Opened 2024-09-24 16:41 UTC by maxsokolovsky

This ensures that the main query and the conditionally run subsequent count query are within the same transaction context.
This will make it so that the second query that counts the number of rows returned by the first will always see the actual number, without the possibility of modifications to the data introduced in between query executions.

2024-09-24 20:34 UTC, maxsokolovsky commented
@moio, I've had to re-generate the same interface as a mock in the package where I have the main test. Looks like there are a few instances where a single interface has multiple mock implementations. Are they all needed? Or do we do this just because Go doesn't allow to import exported types defined in **test** code? If so, could we extract mocks to a non-test package?

2024-09-27 14:02 UTC, moio commented
I share the feeling current code is using a lot of almost-duplicated interfaces and mocking, and that at times confuses me as well.

I value any step big or small to make interfaces and tests more understandable.

About extracting mocks to a non-test package: I have no problems with that, I am not aware of side effects other than not being immediately clear from the filename that the code in question is test code. I am completely OK if that message is conveyed to readers in some other way, eg. with type and function names.

2024-09-27 14:11 UTC, moio commented on pkg/cache/sql/informer/listoption_indexer.go
> +			_ = tx.Cancel()
Being a bit picky: Cancel (actually Rollback) might return an error different from the query error, and we might want to expose both.

Ideally capture the err here, and make sure it is wrapped into the returned error if possible.

Thanks!

2024-10-01 14:43 UTC, moio approved these changes
LGTM. In future, we might want to extract the common code for canceling transactions and handling errors in a helper/utility function, but I do not see it as necessary before this can be merged.

2024-11-07 22:11 UTC, ericpromislow requested changes
Wondering if we can just call `tx.Rollback()` after a group of queries, as there's nothing to change in the database.

2024-11-08 09:42 UTC, moio commented
@ericpromislow we can - after a group of read-only queries commit and rollback are synonymous.

Are you suggesting any change in this PR?

2024-11-08 19:44 UTC, prachidamle commented
This PR is part of https://github.com/rancher/rancher/issues/46410

2024-11-09 00:57 UTC, ericpromislow approved these changes
Let's get this change in and later change useless `Commit`s to `Rollback`s after only reads

2024-11-09 00:57 UTC, merged