updated k8s-deps to 0.27.4
rancher/lasso pull request #51
Opened 2023-08-17 11:47 UTC by vardhaman22

2023-08-18 21:26 UTC, jiaqiluo requested changes
We need to bump dependencies in `controller-runtime/go.mod`

2023-08-18 21:27 UTC, kinarashah requested changes
Since rancher will be updated to use capi v1.5.0, we'd also need to update corresponding controller-runtime version in lasso. https://github.com/kubernetes-sigs/cluster-api/blob/v1.5.0/go.mod#L46 

https://github.com/rancher/lasso/pull/48 has partial update to v0.14.0 for reference

2023-08-19 01:33 UTC, jiaqiluo approved these changes
LGTM

2023-08-22 18:12 UTC, kinarashah approved these changes

2023-08-30 16:44 UTC, merged